name: Build LaTeX and commit PDF

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
      - 'latex/**'        # adjust to match your project structure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # so we can push commits

    - name: Set up TeXLive and compile
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex   # <- change to your main tex filename

    - name: Verify PDF exists
      run: |
        if [ ! -f main.pdf ]; then
          echo "PDF not produced!"; ls -la
          exit 1
        fi

    - name: Commit and push generated PDF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # move or copy pdf to desired location
        mkdir -p build
        cp -f main.pdf build/main.pdf
        git add build/main.pdf
        # check if changes
        if git diff --cached --quiet; then
          echo "No PDF changes to commit."
        else
          git commit -m "Build: update PDF (compiled by GitHub Actions)"
          git push
        fi
